config/routes.rb
TaskManagement::Application.routes.draw do

  scope '(:locale)' do

    resources :comments, :except => [:index, :destroy, :show ]

    resources :tasks, :except => [:index, :destroy]

    resources :sprints, :except => [:index, :destroy]

    resources :releases, :except => [:index, :destroy]

    resources :projects do 
      get :new_members, on: :member, as: :new_members
      put :create_members, on: :member, as: :create_members
      get :tasks, on: :member, as: :tasks
    end

    devise_for :users,
      :controllers => {
        :sessions => "sessions",
        :registrations => "registrations"
      }

    root to: 'projects#index'
  end  
  
  resources :users, :except => [:new, :create]

  

end

app/models/task.rb
class Task < ActiveRecord::Base

	AVAILABLE_STATUS = %w( defined inprogress completed accepted rejected )
	
	has_many :comments, dependent: :destroy
	belongs_to :sprint
	belongs_to :user

	validates_inclusion_of :status, in: %w( defined inprogress completed accepted rejected ), message: ':the task must be on one of "defined, inprogress, completed, accepted and rejected" statuses'
	accepts_nested_attributes_for :comments, allow_destroy: true

	attr_accessible :comments_attributes, :subject, :description, :status, :sprint_id, :assignee_id, :attachment

	has_attached_file :attachment

	def project_members
		begin
			sprint.release.project.users
		rescue
			[]
		end
	end

end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  
  load_and_authorize_resource

  # GET /tasks/1
  # GET /tasks/1.json
  def show
    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @task }
    end
  end

  # GET /tasks/new
  # GET /tasks/new.json
  def new
    @task = Task.new
    @sprint_id = params[:sprint_id]
    @assignee_id = current_user.id
    if(@sprint_id)
      respond_to do |format|
        format.html # new.html.erb
        format.json { render json: @task }
      end
    else
      redirect_to projects_path, notice: "can't create independent tasks"
    end
  end

  # GET /tasks/1/edit
  def edit
    @sprint_id = @task.sprint_id
    @assignee_id = @task.assignee_id
    redirect_to projects_path,notice:("can't edit independent tasks") unless @sprint_id
  end

  # POST /tasks
  # POST /tasks.json
  def create
    sprint = Sprint.find(params[:task][:sprint_id])
    project = current_user.projects.find(sprint.release.project_id)
    @task = Task.new(params[:task])

    respond_to do |format|
      if @task.save
        format.html { redirect_to sprint_path(@task.sprint_id), notice: 'Task was successfully created.' }
        format.json { render json: @task, status: :created, location: @task }
      else
        @sprint_id = params[:task][:sprint_id]
        format.html { render action: "new" }
        format.json { render json: @task.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /tasks/1
  # PUT /tasks/1.json
  def update
    sprint = Sprint.find(@task.sprint_id)
    project = current_user.projects.find(sprint.release.project_id)

    respond_to do |format|
      if @task.update_attributes(params[:task])
        format.html { redirect_to sprint_path(@task.sprint_id), notice: 'Task was successfully updated.' }
        format.json { head :ok }
      else
        @sprint_id = @task.sprint_id
        format.html { render action: "edit" }
        format.json { render json: @task.errors, status: :unprocessable_entity }
      end
    end
  end
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/views/tasks/_comment.html.erb
<li class="hide_this">
	<h4> 
	  comment
	  <%= b.link_to_remove"remove" %>
	</h4>

	<%= b.text_field :content %>       

</li>

app/views/tasks/_comments.html.erb
<ul>
	<% counter = 0%>
    <%= f.fields_for :comments do |b| %>
      <li class="hide_this">
      	<% counter += 1%>
		<h4> 
		  comment <%= counter %>
		  <%= link_to_remove_fields "remove", b %>
		</h4>

		<%= b.text_field :content %>       
		
      </li>
    <% end %>
</ul>

app/views/tasks/_form.html.erb
<%= nested_form_for @task, :html => {:multipart => true} do |f| %>
  <% if @task.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@task.errors.count, "error") %> prohibited this task from being saved:</h2>

      <ul>
      <% @task.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <%= f.hidden_field :sprint_id , value: @sprint_id %>
  <%= f.hidden_field :assignee_id , value: @assignee_id %>

  <div class="field">
    <%= f.label :subject %><br />
    <%= f.text_field :subject %>
  </div>
  <div class="field">
    <%= f.label :status %><br />
    <%= f.select :status, Task::AVAILABLE_STATUS, prompt: "state the status of the task" %>
  </div>
  <div class="field">
    <%= f.label :description %><br />
    <%= f.text_area :description %>
  </div>

  <div class="field">
    <%= f.file_field :attachment %>
  </div>
  
  <%= render '/layouts/nested_attributes', f: f, assoc: :comments %>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/tasks/edit.html.erb
<h1>Editing task</h1>

<%= render 'form' %>

<%= link_to 'Show', task_path(@task) %> |
<%= link_to 'Back', sprint_path(@task.sprint_id) %>

app/views/tasks/index.html.erb
<h1>Listing tasks</h1>

<table>
  <tr>
    <th>Subject</th>
    <th>Description</th>
    <th>Status</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @tasks.each do |task| %>
  <tr>
    <td><%= task.subject %></td>
    <td><%= task.description %></td>
    <td><%= task.status %></td>
    <td><%= link_to 'Show', task %></td>
    <td><%= link_to 'Edit', edit_task_path(task) %></td>
    <td><%= link_to 'Destroy', task, confirm: 'Are you sure?', method: :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Task', new_task_path %>

app/views/tasks/new.html.erb
<h1>New task</h1>

<%= render 'form' %>

<%= link_to 'Back', :back %>

app/views/tasks/show.html.erb
<p>
  <b>Subject:</b>
  <%= @task.subject %>
</p>

<p>
  <b>Status:</b>
  <%= @task.status %>
</p>

<p>
  <b>Description:</b>
  <%= @task.description %>
</p>

<ul>
	<% @task.comments.each do |comment| %>
		<li> <p>  <%=comment.content%> </p> </li>
	<% end %>
</ul>

<% if @task.attachment.size%>
<%= link_to 'See attachment', @task.attachment.url(:original), target: "_blank" %>
<% end %>


<%= form_tag new_comment_path , method: :get do %>
	<%= hidden_field_tag :task_id, @task.id %>
	<%= submit_tag 'Add new comment' %>
<% end %>
<br/>


<%= link_to 'Edit', edit_task_path(@task) %> |
<%= link_to 'Back', sprint_path(@task.sprint_id) %>