config/routes.rb
TaskManagement::Application.routes.draw do

  scope '(:locale)' do

    resources :comments, :except => [:index, :destroy, :show ]

    resources :tasks, :except => [:index, :destroy]

    resources :sprints, :except => [:index, :destroy]

    resources :releases, :except => [:index, :destroy]

    resources :projects do 
      get :new_members, on: :member, as: :new_members
      put :create_members, on: :member, as: :create_members
      get :tasks, on: :member, as: :tasks
    end

    devise_for :users,
      :controllers => {
        :sessions => "sessions",
        :registrations => "registrations"
      }

    root to: 'projects#index'
  end  
  
  resources :users, :except => [:new, :create]

  

end

app/models/sprint.rb
class Sprint < ActiveRecord::Base
	has_many :tasks, dependent: :destroy
	belongs_to :release

	accepts_nested_attributes_for :tasks, allow_destroy: true

	attr_accessible :tasks_attributes, :start_date, :end_date, :release_id

	def project_members
		begin
			release.project.users
		rescue
			[]
		end
	end

end

app/controllers/sprints_controller.rb
class SprintsController < ApplicationController
  
  load_and_authorize_resource

  def show
    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @sprint }
    end
  end

  # GET /sprints/new
  # GET /sprints/new.json
  def new
    @sprint = Sprint.new
    @release_id = params[:release_id]
    if(@release_id)
      respond_to do |format|
        format.html # new.html.erb
        format.json { render json: @sprint }
      end
    else
      redirect_to projects_path,
        notice: "can't create independent sprints"
    end
  end

  # GET /sprints/1/edit
  def edit
    @release_id = @sprint.release_id
    redirect_to projects_path,
      notice:("can't edit independent sprints") unless @release_id
  end

  # POST /sprints
  # POST /sprints.json
  def create
    release = Release.find(params[:sprint][:release_id])
    project = current_user.projects.find(release.project_id)
    @sprint = Sprint.new(params[:sprint])

    respond_to do |format|
      if @sprint.save
        format.html { redirect_to release_path(@sprint.release_id), notice: 'Sprint was successfully created.' }
        format.json { render json: @sprint, status: :created, location: @sprint }
      else
        @release_id = params[:sprint][:release_id]
        format.html { render action: "new" }
        format.json { render json: @sprint.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /sprints/1
  # PUT /sprints/1.json
  def update
    release = Release.find(@sprint.release_id)
    project = current_user.projects.find(release.project_id)

    respond_to do |format|
      if @sprint.update_attributes(params[:sprint])
        format.html { redirect_to release_path(@sprint.release_id), notice: 'Sprint was successfully updated.' }
        format.json { head :ok }
      else
        @release_id = @sprint.release_id
        format.html { render action: "edit" }
        format.json { render json: @sprint.errors, status: :unprocessable_entity }
      end
    end
  end
end

app/helpers/sprints_helper.rb
module SprintsHelper
end

app/views/sprints/_form.html.erb
<%= nested_form_for(@sprint) do |f| %>
  <% if @sprint.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@sprint.errors.count, "error") %> prohibited this sprint from being saved:</h2>

      <ul>
      <% @sprint.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <%= f.hidden_field :release_id , value: @release_id %>

  <div class="field">
    <%= f.label :start_date %><br />
    <%= f.text_field :start_date, class: :date %>
  </div>
  <div class="field">
    <%= f.label :end_date %><br />
    <%= f.text_field :end_date, class: :date %>
  </div>

  <%= render '/layouts/nested_attributes', f: f, assoc: :tasks %>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/sprints/_task.html.erb
<li class="hide_this">
	<h4> 
	  task
	  <%= b.link_to_remove "remove"%>
	</h4>

	<%= b.label :subject %>
	<%= b.text_field :subject %> <br/>

	<%= b.label :status %>
	<%= b.select :status, Task::AVAILABLE_STATUS, prompt: "state the status of the task" %> <br/>

	<%= b.label :assignee_id %>
	<%= b.select :assignee_id, 
	      options_from_collection_for_select(
	      Release.find(@release_id).project_members, "id","name")%>
	<br/>

	<%= b.label :description %><br/>
	<%= b.text_area :description %><br/>       

	<%= b.file_field :attachment %>
</li>

app/views/sprints/_tasks.html.erb
<ul>
	<% counter = 0%>
    <%= f.fields_for :tasks do |b| %>
      <li class="hide_this">
      	<% counter += 1%>
		<h4> 
		  task <%= counter %>
		  <%= link_to_remove_fields "remove", b %>
		</h4>
		
		<%= b.label :subject %>
		<%= b.text_field :subject %> <br/>

		<%= b.label :status %>
    	<%= b.text_field :status %> <br/>

		<%= b.label :description %>
    	<%= b.text_area :description %><br/>       
      </li>
    <% end %>
</ul>

app/views/sprints/edit.html.erb
<h1>Editing sprint</h1>

<%= render 'form' %>

<%= link_to 'Show', sprint_path(@sprint) %> |
<%= link_to 'Back', release_path(@sprint.release_id) %>

app/views/sprints/index.html.erb
<h1>Listing sprints</h1>

<table>
  <tr>
    <th>Start date</th>
    <th>End date</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @sprints.each do |sprint| %>
  <tr>
    <td><%= sprint.start_date %></td>
    <td><%= sprint.end_date %></td>
    <td><%= link_to 'Show', sprint %></td>
    <td><%= link_to 'Edit', edit_sprint_path(sprint) %></td>
    <td><%= link_to 'Destroy', sprint, confirm: 'Are you sure?', method: :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Sprint', new_sprint_path %>

app/views/sprints/new.html.erb
<h1>New sprint</h1>

<%= render 'form' %>

<%= link_to 'Back', :back %>

app/views/sprints/show.html.erb
<p>
  <b>Start date:</b>
  <%= @sprint.start_date %>
</p>

<p>
  <b>End date:</b>
  <%= @sprint.end_date %>
</p>

<ul>
	<% counter = 0%>
	<% @sprint.tasks.each do |task| %>
		<li>
			<% counter += 1%>
			<h4> 
				task <%= counter %> 
				<%= link_to 'Show', task %> |
				<%= link_to 'Edit', edit_task_path(task) %> |
				<!-- <%= link_to 'Delete', task , method: :delete %> -->
			</h4>
			<p> <b> Subject:</b> <%=task.subject%> </p>
			<p> <b> Status: </b> <%=task.status%>  </p>
			<p> 
				<b> Description:</b> <br/>
				<%=task.description%>
			</p>

		</li>
	<% end %>
</ul>


<%= form_tag new_task_path , method: :get do %>
	<%= hidden_field_tag :sprint_id, @sprint.id %>
	<%= submit_tag 'Add new task' %>
<% end %>
<br/>

<%= link_to 'Edit', edit_sprint_path(@sprint) %> |
<%= link_to 'Back', release_path(@sprint.release_id) %>