config/routes.rb
TaskManagement::Application.routes.draw do

  scope '(:locale)' do

    resources :comments, :except => [:index, :destroy, :show ]

    resources :tasks, :except => [:index, :destroy]

    resources :sprints, :except => [:index, :destroy]

    resources :releases, :except => [:index, :destroy]

    resources :projects do 
      get :new_members, on: :member, as: :new_members
      put :create_members, on: :member, as: :create_members
      get :tasks, on: :member, as: :tasks
    end

    devise_for :users,
      :controllers => {
        :sessions => "sessions",
        :registrations => "registrations"
      }

    root to: 'projects#index'
  end  
  
  resources :users, :except => [:new, :create]

  

end

app/models/project.rb
class Project < ActiveRecord::Base

	has_ancestry

	 before_save :set_identifier 

	validates :name, uniqueness: :true
	validate :depth_must_be_at_most_one
	validate :parent_project
	

	has_and_belongs_to_many :users
	has_many :releases, dependent: :destroy

	accepts_nested_attributes_for :users
	
	accepts_nested_attributes_for :releases, allow_destroy: true

	attr_accessible :releases_attributes, :name, :start_date, :end_date,
			:parent_id
	
	def depth_must_be_at_most_one
		errors.add(:base," can't create subproject of subproject") if depth > 1
	end

	def parent_project
		if parent and parent.creator_id != self.creator_id
			errors.add(:base," can't create subproject of non-owned project")
		end
	end

	def to_param
		identifier
	end

	def set_identifier
		self.identifier = self.name.parameterize
	end


end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  load_and_authorize_resource find_by: :identifier

  # GET /projects
  # GET /projects.json
  def index
    if user_signed_in?
      @search = current_user.projects.search(params[:search])
    else
      @search = Project.search(params[:search])
    end

    @projects = @search.paginate per_page: 15, page: params[:page],
          order: "name"

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @projects }
    end
  end

  # GET /projects/1
  # GET /projects/1.json
  def show
    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @project }
    end
  end

  # GET /projects/new
  # GET /projects/new.json
  def new

    @project = Project.new
    @main_projects = Project.roots.where(creator_id: current_user.id)

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @project }
    end
  end

  # GET /projects/1/edit
  def edit
    @main_projects = Project.roots.where(creator_id: @project.creator_id)
  end

  # POST /projects
  # POST /projects.json
  def create
    @project = Project.new(params[:project])
    @project.creator_id = current_user.id	  
    respond_to do |format|
      if @project.save
        @project.users << current_user
        format.html { redirect_to project_path(@project), notice: 'Project was successfully created.' }
        format.json { render json: @project, status: :created, location: @project }
      else
        @main_projects = Project.roots.where(creator_id: @project.creator_id)
        format.html { render action: "new" }
        format.json { render json: @project.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /projects/1
  # PUT /projects/1.json
  def update
    respond_to do |format|
      if @project.update_attributes(params[:project])
        format.html { redirect_to @project, notice: 'Project was successfully updated.' }
        format.json { head :ok }
      else
        @main_projects = Project.roots.where(creator_id: @project.creator_id)
        format.html { render action: "edit" }
        format.json { render json: @project.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /projects/1
  # DELETE /projects/1.json
  def destroy
    # @project = Project.find(params[:id])
    @project.destroy

    respond_to do |format|
      format.html { redirect_to projects_url }
      format.json { head :ok }
    end
  end

  # put /projects/:id/new_members
  # put //projects/:id/new_members.json
  def new_members
    @members = User.all
  end


  # put /projects/:id/create_members
  # put //projects/:id/create_members.json
  def create_members
    project = Project.find(params[:id])

    params[:members].each do |member_id|
      user = User.find(member_id)
      project.users << user unless project.users.include?(user)  
    end
    
    respond_to do |format|
      format.html { redirect_to project_path(@project), notice: 'members were successfully added.' }
      format.json { render json: @project, status: :created, location: @project }
    end
  end

  def tasks
  end

end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/views/projects/_form.html.erb
<%= nested_form_for(@project) do |f| %>
  
  <% if @project.errors.any? %>
    <div id="error_explanation">
      <h2>
        <%= pluralize(@project.errors.count, "error") %> prohibited this project from being saved:
      </h2>

      <ul>
      <% @project.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :start_date %><br />
    <%= f.text_field :start_date, class: :date %>
  </div>
  <div class="field">
    <%= f.label :end_date %><br />
    <%= f.text_field :end_date, class: :date %>
  </div>
  <div class="field">
    <%= f.label :parent_id %><br />
    <%= f.select :parent_id, 
        options_from_collection_for_select(@main_projects,"id","name"),
        prompt: 'it is a main project' %>
  </div>

  
  <%= render '/layouts/nested_attributes', f: f, assoc: :releases %>
  
  <div class="actions">
    <%= f.submit %>
  </div>
  
<% end %>

app/views/projects/_release.html.erb
<li class="hide_this">
	<h4> 
	  release
	  <%= b.link_to_remove "remove"%>
	</h4>

	<%= b.label :version %>
	<%= b.text_field :version %> <br/>
	    
	<%= b.label :start_date %>
	<%= b.text_field :start_date, class: :date %> <br/>

	<%= b.label :end_date %>
	<%= b.text_field :end_date, class: :date %><br/>
</li>

app/views/projects/_releases.html.erb
<ul class="nested_attributes">

    <%= f.fields_for assoc do |b| %>
    	<% partial = assoc.to_s.singularize%>
      <%= render "#{partial}", b: b %>
    <% end %>
</ul>

app/views/projects/edit.html.erb
<h1>Editing project</h1>

<div class="edit_project_form">
	<%= render 'form' %>
</div>

<%= link_to 'Show', @project %> |
<%= link_to 'Back', projects_path %>

app/views/projects/index.html.erb
<h1>Listing projects</h1>

<fieldset class="projects-filters">
  <% c_id = params[:search][:creator_id_eq] if params[:search] %>
  <legend> <%= t('.filter') %> </legend>
  <%= form_for @search, url: projects_path, :html => {:method => :get} do |f| %>
    <%= f.label :name_contains, t('.name_contains') %>
    <%= f.text_field :name_contains %><br />
    <%= f.label :creator_name, t('.creator_name') %>
    <%= f.select :creator_id_eq,
          options_for_select(Admin.all.collect {|p| [ p.name, p.id ] }, c_id),
            include_blank: true %> <br/>
    <%= f.label :release_version, t('.release_version') %>
    <%= f.text_field :releases_version_contains %> <br/>      
    <%= f.submit %>
  <% end %>
</fieldset>

<table>
  <tr>
    <th><%= t('.name') %></th>
    <th><%= t('.start_date') %></th>
    <th><%= t('.end_date') %></th>
    <th><%= t('.creator') %></th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @projects.each do |project| %>
<% project.reload %>
  <tr>
    <td><%= project.name %></td>
    <td><%= project.start_date %></td>
    <td><%= project.end_date %></td>
    <td><%= User.find(project.creator_id).name %></td>
    <td><%= link_to t('.show'), project %></td>
    <td><%= link_to t('.edit'), edit_project_path(project) %></td>
    <td><%= link_to t('.destroy'), project, confirm: t('.confirm'), method: :delete %></td>
    
  </tr>
<% end %>
</table>

<br />

<%= link_to t('.new_project'), new_project_path %>
<%= will_paginate(@projects) %>

app/views/projects/new.html.erb
<h1>New project</h1>

<%= render 'form' %>

<%= link_to 'Back', projects_path %>

app/views/projects/new_members.html.erb
<div id="project-members">
	
		<p> choose from the list to assign project members to <%= @project.name%> </p>

		<%= select_tag :project_members, 
         options_from_collection_for_select(@members,"_id","name"),
        prompt: 'add members to the project', id: :select_members%>

		<%=form_tag create_members_project_path, method: :put, id: :members_list do%>
			<%= submit_tag 'Save', id: :save%>	
		<% end %>

</div>

app/views/projects/release.js.erb
 $('.edit_project_form').html("<%=j render 'form' %>");

app/views/projects/show.html.erb
<p>
  <b>Name:</b>
  <%= @project.name %>
</p>

<p>
  <b>Start date:</b>
  <%= @project.start_date %>
</p>

<p>
  <b>End date:</b>
  <%= @project.end_date %>
</p>

<ul>
	<% counter = 0%>
	<% @project.releases.each do |release| %>
		<li>
			<% counter += 1%>
			<h4> 
				release <%= counter %> 
				<%= link_to 'Show', release %> |
				<%= link_to 'Edit', edit_release_path(release) %> |
				<!--<%= link_to 'Delete', release , method: :delete %>-->
			</h4>
			<p> <b> version:   </b> <%=release.version%>    </p>
			<p> <b> started at:</b> <%=release.start_date%> </p>
			<p> <b> ended at:  </b> <%=release.end_date%>    </p>			    
		</li>
	<% end %>
</ul>



<%= form_tag new_release_path , method: :get do %>
	<%= hidden_field_tag :project_id, @project.id %>
	<%= submit_tag 'Add new release' %>
<% end %>

<%= form_tag new_members_project_path , method: :get do %>
	<%= hidden_field_tag :project_id, @project.id %>
	<%= submit_tag 'project members' %>
<% end %>
<br/>

<%= link_to 'View Tasks', tasks_project_path(@project) %> |
<%= link_to 'Edit', edit_project_path(@project) %> |
<%= link_to 'Back', projects_path %>

app/views/projects/tasks.html.erb
<P> tasks of <%= @project.name%></P>
<ul>
	<% @project.releases.each do |release| %>
		<li> <%= release.version %>
				<ul>
					<% release.sprints.each do |sprint| %>
						<li> sprint <%=sprint.start_date%> to <%=sprint.end_date%>
							<ul>
								<% sprint.tasks.each do |task| %>
									<li>
										<p>
										  <b>Subject:</b>
										  <%= task.subject %>
										</p>

										<p>
										  <b>Status:</b>
										  <%= task.status %>
										</p>

										<p>
										  <b>Description:</b>
										  <%= task.description %>
										</p>
									</li>
								<% end %>
							</ul>
						</li>
					<% end %>
				</ul>
		</li>
	<% end %>
</ul>